# Generated by Django 5.2.11 on 2026-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200),
            preserve_default=False,
        ),
    ]
